import type { Program, Testimonial, Benefit, FAQItem } from "./types"

export const PROGRAMS: Program[] = [
  {
    id: "administracion-empresas",
    name: "Licenciatura en Administración de Empresas",
    duration: "3 años 4 meses",
    modality: "online",
    nextCohort: "Próximo inicio disponible",
    price: "$2,000 MXN/mes",
    description:
      "Forma líderes empresariales capaces de optimizar operaciones, gestionar recursos y tomar decisiones estratégicas.",
    curriculum: [
      "Incorporación a la Tecnología de Información y Sistemas de Gestión del Aprendizaje LMS",
      "Metodología De La Investigación",
      "Taller De Lectura Y Redacción",
      "Ética Y Práctica Profesional",
      "Contabilidad General",
      "Introducción al Estudio del Derecho",
      "Matemáticas Financieras",
      "Temas Básicos de Administración",
      "Administración de Negocios",
      "Derecho Mercantil",
      "Estadística",
      "Estructura Organizacional",
      "Costos y Evaluación de Proyecto",
      "Economía Contemporánea",
      "Sistemas y Procedimientos Administrativos",
      "Informática Aplicada a la Administración",
      "Administración de Recursos Humanos",
      "Contabilidad Administrativa",
      "Derecho Laboral",
      "Presupuestos",
      "Administración Financiera",
      "Administración de la Producción",
      "Investigación de Operaciones",
      "Mercadotecnia",
      "Auditoría Administrativa",
      "Administración de la Micro, Pequeña y Mediana Empresa",
      "Derecho Fiscal",
      "Estrategias de Mercadotecnia",
      "Análisis e Interpretación de Estados Financieros",
      "Auditoría Operacional",
      "Compras y Abastecimientos",
      "Investigación de Mercados",
      "Organizaciones que Aprenden",
      "Planeación Estratégica",
      "Procesos de la Calidad",
      "Seminario de Trabajo de Titulación",
      "Desarrollo de Habilidades Gerenciales",
      "Formulación y Evaluación de Proyectos de Inversión",
      "Responsabilidad Social de la Empresa",
      "Taller de Trabajo de Titulación",
    ],
    outcomes: [
      "Optimizar operaciones: Identificar y mejorar procesos para aumentar la eficiencia",
      "Gestionar recursos: Asignar y controlar recursos de manera efectiva",
      "Fomentar una cultura organizacional positiva: Crear un ambiente de trabajo productivo y motivador",
      "Tomar decisiones estratégicas: Evaluar opciones y seleccionar las mejores para alcanzar objetivos",
      "Emprender tu propio negocio o trabajar en empresas nacionales de cualquier tamaño",
      "Trabajar en empresas familiares, PyMES, de manufactura, comercio o servicios",
      "Colaborar con ONGs, fundaciones o asociaciones",
    ],
  },
  {
    id: "contaduria",
    name: "Licenciatura en Contaduría",
    duration: "3 años 4 meses",
    modality: "online",
    nextCohort: "Próximo inicio disponible",
    price: "$2,000 MXN/mes",
    description:
      "Forma expertos en análisis financiero, gestión de riesgos y planificación estratégica para garantizar la estabilidad empresarial.",
    curriculum: [
      "Incorporación a la Tecnología de Información y Sistemas de Gestión del Aprendizaje LMS",
      "Metodología de la Investigación",
      "Taller de Lectura y Redacción",
      "Ética y Práctica Profesional",
      "Contabilidad I",
      "Introducción al Estudio del Derecho",
      "Matemáticas Financieras",
      "Temas Fundamentales de Administración",
      "Contabilidad II",
      "Derecho Mercantil",
      "Estadística",
      "Estructura Organizacional",
      "Contabilidad III",
      "Contabilidad de Sociedades",
      "Investigación de Operaciones",
      "Microeconomía",
      "Costos I",
      "Derecho Laboral",
      "Impuestos I",
      "Macroeconomía",
      "Costos II",
      "Finanzas I",
      "Impuestos II",
      "Software Contable",
      "Costos III",
      "Estados Financieros",
      "Finanzas II",
      "Impuestos III",
      "Administración de Cartera",
      "Auditoría I",
      "Contabilidades Especiales",
      "Impuestos IV",
      "Auditoría II",
      "Presupuestos",
      "Simulaciones Financieras",
      "Seminario de Trabajo de Titulación",
      "Administración Financiera",
      "Contribución a los Salarios",
      "Mercados Financieros",
      "Taller de Trabajo de Titulación",
    ],
    outcomes: [
      "Análisis financiero: Descifrar los números y tomar decisiones basadas en datos sólidos",
      "Gestión de riesgos: Identificar y mitigar riesgos financieros para garantizar la estabilidad de las empresas",
      "Optimización de recursos: Maximizar la rentabilidad y eficiencia de los recursos financieros",
      "Planificación estratégica: Diseñar estrategias financieras que impulsan el crecimiento de las organizaciones",
      "Trabajar como asesor de negocios o consultor de empresas",
      "Desempeñarse como auditor de estados financieros o perito forense contable",
      "Ser asesor de inversiones en el sector gubernamental o privado",
    ],
  },
  {
    id: "derecho",
    name: "Licenciatura en Derecho",
    duration: "3 años 4 meses",
    modality: "online",
    nextCohort: "Próximo inicio disponible",
    price: "$2,000 MXN/mes",
    description:
      "Formación integral con sólidos conocimientos jurídicos y visión crítica para resolver conflictos y construir una sociedad más justa.",
    curriculum: [
      "Incorporación a la Tecnología de Información y Sistemas de Gestión del Aprendizaje LMS",
      "Metodología de la Investigación",
      "Taller de Lectura y Redacción",
      "Ética y Práctica Profesional",
      "Introducción al Estudio del Derecho",
      "Derecho Romano",
      "Sociología Jurídica",
      "Economía Política",
      "Teoría General del Proceso",
      "Taller de Redacción Jurídica",
      "Derecho Civil I",
      "Derechos Humanos",
      "Derecho Civil II",
      "Derecho Penal I",
      "Derecho del Trabajo",
      "Derecho Constitucional I",
      "Derecho Civil III",
      "Derecho Penal II",
      "Derecho Procesal del Trabajo",
      "Derecho Constitucional II",
      "Derecho Informático",
      "Derecho Civil IV",
      "Derecho Mercantil I",
      "Derecho Administrativo",
      "Derecho Procesal Civil",
      "Derecho Mercantil II",
      "Derecho Fiscal",
      "Derecho Internacional Público y Privado",
      "Derecho Procesal Mercantil",
      "Derecho Procesal Penal",
      "Derecho Económico",
      "Derecho de la Seguridad Social",
      "Derecho Notarial y Registral",
      "Juicios Orales en Materia Penal",
      "Derecho de Amparo",
      "Seminario de Trabajo de Titulación",
      "Criminología y Criminalística",
      "Medicina Forense",
      "Derecho Financiero",
      "Taller de Trabajo de Titulación",
    ],
    outcomes: [
      "Dominar el marco jurídico, tanto en el ámbito público como privado",
      "Desarrollar habilidades de investigación para analizar casos y diseñar estrategias legales efectivas",
      "Comprender el contexto social, abordando los desafíos legales desde una perspectiva multidimensional",
      "Colaborar con otros profesionales y encontrar soluciones innovadoras a los problemas legales",
      "Trabajar en despachos de abogados especializados o de regulación tecnológica",
      "Desempeñarse en el área legal de diferentes empresas",
      "Trabajar en Tribunales de Justicia, Poder Legislativo o Administración pública",
      "Colaborar con organizaciones no gubernamentales",
    ],
  },
  {
    id: "marketing",
    name: "Licenciatura en Marketing",
    duration: "3 años 4 meses",
    modality: "online",
    nextCohort: "Próximo inicio disponible",
    price: "$2,000 MXN/mes",
    description:
      "Forma profesionales integrales con dominio del marketing tradicional y digital, adaptándose a la evolución constante de los medios digitales.",
    curriculum: [
      "Incorporación a la Tecnología de Información y Sistemas de Gestión del Aprendizaje LMS",
      "Desarrollo de Habilidades Directivas",
      "Supuestos del Comportamiento Social",
      "Bases Metodológicas de Investigación",
      "Desarrollo Estratégico y Liderazgo",
      "Estrategias de Social Media",
      "Mercadotecnia",
      "Informática Aplicada a la Mercadotecnia",
      "Marcas Digitales",
      "Plataformas Digitales",
      "Planeación Estratégica",
      "Desarrollo de Marcas y Merchandising",
      "Costos, Presupuestos y Estrategia de Fijación de Precios",
      "Emprendedores",
      "Segmentación y Valoración de Mercados Potenciales",
      "Investigación Cualitativa de Mercados",
      "E-Products",
      "Financiamiento de Plan de Negocios",
      "Innovación y Desarrollo de Productos",
      "Ventas en Mercados Digital",
      "Estrategias de Precios",
      "Logística y Distribución en Ventas Electrónicas",
      "Marco Legal de la Mercadotecnia y Publicidad",
      "Planeación de Campañas de Marketing Digital",
      "Consumo Online y Multiculturalidad",
      "Legislación en Entornos Virtuales",
      "Protocolos para Comunidades Virtuales",
      "Toma de Decisiones Estratégicas",
      "Alta Dirección y Couching",
      "Aplicaciones de Diseño Digital",
      "Branding y Posicionamiento On Line",
      "Estrategias Comerciales E Comunidades de Red",
      "Dirección Comercial",
      "Ética y Práctica Profesional",
      "Innovación en Productos y Servicios",
      "Modelos y Estrategias de CRM",
      "Accountability En Medios Digitales",
      "Plan de Medios",
      "Negociación y Resolución de Conflictos",
      "Viabilidad Financiera de Proyectos de Comercialización y Ventas",
    ],
    outcomes: [
      "Sólido conocimiento en áreas como administración, economía, contabilidad y finanzas",
      "Habilidades analíticas, creatividad, comunicación, orientación a resultados y adaptabilidad",
      "Dominio de los principios del marketing tradicional y digital",
      "Adaptarse a la constante evolución de los medios digitales",
      "Trabajar en agencias de publicidad y promoción",
      "Especializarse en investigación de mercados",
      "Desarrollar mercadotecnia en empresas o agencias de relaciones públicas",
      "Trabajar en agencias digitales o medios de comunicación como radios, televisión, plataformas digitales",
    ],
  },
  {
    id: "economia",
    name: "Licenciatura en Economía",
    duration: "3 años 4 meses",
    modality: "online",
    nextCohort: "Próximo inicio disponible",
    price: "$2,000 MXN/mes",
    description:
      "Desarrolla comprensión científica rigurosa de la cultura económica con herramientas cuantitativas y orientación a la investigación.",
    curriculum: [
      "Incorporación a la Tecnología de Información y Sistemas de Gestión del Aprendizaje LMS",
      "Metodología de la Investigación",
      "Taller de Lectura y Redacción",
      "Ética y Práctica Profesional",
      "Fundamentos de Economía",
      "Matemáticas para Economistas",
      "Estadística Económica",
      "Microeconomía I",
      "Macroeconomía I",
      "Historia del Pensamiento Económico",
      "Microeconomía II",
      "Macroeconomía II",
      "Econometría I",
      "Economía Internacional",
      "Finanzas Públicas",
      "Economía Monetaria",
      "Econometría II",
      "Desarrollo Económico",
      "Economía Laboral",
      "Economía Industrial",
      "Evaluación de Proyectos",
      "Economía Ambiental",
      "Seminario de Investigación Económica",
      "Taller de Trabajo de Titulación",
    ],
    outcomes: [
      "Desarrollar comprensión científica rigurosa de la cultura económica",
      "Aplicar herramientas cuantitativas como matemáticas, estadística y econometría",
      "Desarrollar un perfil orientado a la investigación",
      "Adquirir sólidas habilidades para la resolución de problemas económicos",
      "Comprometerse con los desafíos económicos nacionales y globales",
      "Trabajar en Secretarías de Estado y organismos descentralizados",
      "Desempeñarse en instituciones financieras como bancos, aseguradoras, casas de bolsa",
      "Colaborar en centros de educación superior e investigación",
      "Trabajar en empresas de consultoría del sector privado",
      "Participar en organizaciones sociales y no gubernamentales",
    ],
  },
]

export const TESTIMONIALS: Testimonial[] = [
  {
    id: "1",
    name: "María González",
    program: "Administración de Empresas",
    cohort: "2023",
    quote: "ULINEA me dio las herramientas para crecer profesionalmente. Hoy dirijo mi propia empresa.",
    image: "/professional-business-woman.jpg",
    role: "CEO",
    company: "TechStart Solutions",
  },
  {
    id: "2",
    name: "Carlos Rodríguez",
    program: "Marketing Digital",
    cohort: "2022",
    quote: "La flexibilidad de estudiar online me permitió trabajar mientras me formaba.",
    image: "/professional-business-man.jpg",
    role: "Marketing Manager",
    company: "Digital Agency",
  },
  {
    id: "3",
    name: "Ana Martínez",
    program: "Ingeniería en Sistemas",
    cohort: "2024",
    quote: "Los profesores son expertos en la industria. Aprendí tecnologías de vanguardia.",
    image: "/professional-woman-engineer.png",
    role: "Software Developer",
    company: "Tech Corp",
  },
]

export const BENEFITS: Benefit[] = [
  {
    id: "1",
    title: "Flexibilidad Total",
    description: "Estudia a tu ritmo, desde donde quieras, cuando quieras.",
    icon: "clock",
  },
  {
    id: "2",
    title: "Profesores Expertos",
    description: "Aprende de profesionales activos en la industria.",
    icon: "users",
  },
  {
    id: "3",
    title: "Proyectos Reales",
    description: "Trabaja en casos reales de empresas durante tu formación.",
    icon: "briefcase",
  },
  {
    id: "4",
    title: "Red de Contactos",
    description: "Conecta con profesionales y empresas de toda Latinoamérica.",
    icon: "network",
  },
  {
    id: "5",
    title: "Certificación Internacional",
    description: "Títulos reconocidos internacionalmente.",
    icon: "award",
  },
  {
    id: "6",
    title: "Empleabilidad 95%",
    description: "El 95% de nuestros graduados consigue empleo en 6 meses.",
    icon: "trending-up",
  },
]

export const FAQ_ITEMS: FAQItem[] = [
  {
    id: "1",
    question: "¿Cómo funcionan las clases online?",
    answer:
      "Nuestras clases son 100% online con sesiones en vivo y contenido grabado. Puedes acceder desde cualquier dispositivo con internet.",
  },
  {
    id: "2",
    question: "¿Los títulos tienen validez oficial?",
    answer:
      "Sí, todos nuestros programas están acreditados y tienen validez oficial en México y reconocimiento internacional.",
  },
  {
    id: "3",
    question: "¿Puedo trabajar mientras estudio?",
    answer:
      "Absolutamente. Nuestros programas están diseñados para profesionales que trabajan, con horarios flexibles y clases grabadas.",
  },
  {
    id: "4",
    question: "¿Ofrecen becas o financiamiento?",
    answer: "Sí, contamos con diferentes opciones de becas académicas y planes de financiamiento sin intereses.",
  },
  {
    id: "5",
    question: "¿Cuándo inician las próximas cohortes?",
    answer: "Tenemos inicios cada 2 meses. Las próximas fechas son agosto, octubre y diciembre 2025.",
  },
]

// Voice / Contact constants
export const CONTACT = {
  whatsappNumber: "5255960232001",
  whatsappDefaultMessage:
    "¡Hola! Me interesa conocer más sobre los programas de UNAB. ¿Podrían brindarme información?",
}

export const API = {
  chatBaseUrl: process.env.NEXT_PUBLIC_API_URL || "https://web-production-91918.up.railway.app",
}
